name: Push to Container Registry

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:
     branches: [ master ]

jobs:
  push_image:
    # this job will only run if the PR has been merged
    if: (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch') 
    runs-on: ubuntu-20.04
    steps:
      - name: Check the Pull Request 
        if: github.event.pull_request != null 
        run: echo "Event '${{ github.event_name }}' - PR ${{ github.event.pull_request.number }} has been merged"
      
      - name: Check for Manual Launch 
        if: github.event_name == 'workflow_dispatch'
        run: echo "Event '${{ github.event_name }}' - Manual Push to Registry" 
      
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        
      # Test the Docker Image Build
      - name: Build the Image
        run: |
          echo "Build the Docker Image"
          docker build -t rust_builder .

      # Show Compiler Version
      - name: Show Compiler Version
        id: rust_version
        run: | 
          rust_version_info=`docker run -t rust_builder bash -c "rustc --version"`          
          rust_version=`echo "$rust_version_info" | awk '{print $2}'`
          echo "* Rust Compiler Version:" 
          echo "$rust_version_info | $rust_version"
          echo "version=$rust_version" >> $GITHUB_OUTPUT

      # Show Compiler Version
      - name: Set Compiler Version Tag
        id: image_tag
        run: | 
          echo "rustc ver: '${{ steps.rust_version.outputs.version }}'"
          docker tag rust_builder rust_builder:${{ steps.rust_version.outputs.version }}

      - name: Extract metadata (tags, labels) for Docker
        id: image_meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: rust_builder

      # Show Compiler Version
      - name: Show Image Tags and Labels
        run: | 
          echo "* Image Tags:" 
          echo "${{ steps.image_meta.outputs.tags }}"
          echo "* Image Labels:" 
          echo "${{ steps.image_meta.outputs.labels }}"
          echo "* Image Inspection:" 
          docker inspect rust_builder
      
#      - name: Login to DockerHub
#        uses: docker/login-action@v2.1.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push the Image to the Repository
        run: |
          docker tag rust_builder:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

          