name: Build Test

on:
  pull_request:
    # Pull Request events on master branch
    branches: 
      - master
  workflow_dispatch:
     branches:    
      - master  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Configure and Run the Testing Job
  plack-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # List all installed Docker Libraries
      - name: List all installed Docker Libraries
        run: |
          dpkg --get-selections | grep -i docker | sort
       # List all available Docker Libraries
      - name: List all available Docker Libraries
        run: |
          sudo apt-get update 
          sudo apt-cache search docker | sort
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Listing Directory Contents
        run: pwd && ls -lah
        
      # Test the Docker Image Build
      - name: Build the Image
        run: |
          echo "Build the Docker Image"
          docker build -t rust_builder .
